### PR TITLE
Use git repo as source

### PR DESCRIPTION
**Pull request by LyzardKing**

### CODE REVIEW

**Comment by hfiguiere** [comment]
you need to actually build from source.

**Comment by LyzardKing** [comment]
Yes, I noticed that there is no simple way to get gradle working in the flatpak, so in the meantime I'll try and fetch from github assets the latest pre-built

**Comment by LyzardKing** [comment]
@hfiguiere Is it possible to verify the proper functioning of the `x-checker-data` section?

**Comment by hfiguiere** [comment]
I think you can by running the tool:

https://github.com/flathub/flatpak-external-data-checker

(it's available as a flatpak)

**Comment by LyzardKing** [comment]
Ok, with the latest commit it works by pulling the updates from github instead of the fedora release-monitoring

**Comment by LyzardKing** [comment]
This PR does not enable building from source, but it pulls the version from github, with updates sooner than the fedora repo it was looking at earlier.
I also added an auto-merge so that it'll publish automatically the new builds without needing a manual intervention.

**Pull request closed without merging**
